# Generated by Django 4.1.3 on 2022-11-16 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_acc_holder', models.CharField(max_length=250)),
                ('s_bank', models.CharField(max_length=250)),
                ('s_acc_name', models.CharField(max_length=250)),
                ('s_acc_num', models.IntegerField()),
                ('s_purpose', models.TextField()),
                ('savings_account', models.BooleanField()),
                ('s_credit', models.IntegerField()),
                ('s_debit', models.IntegerField()),
                ('s_balance', models.IntegerField()),
                ('s_success', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_acc_holder', models.CharField(max_length=250)),
                ('c_bank', models.CharField(max_length=250)),
                ('c_acc_name', models.CharField(max_length=250)),
                ('c_acc_num', models.IntegerField()),
                ('c_purpose', models.TextField()),
                ('checkings_account', models.BooleanField()),
                ('c_credit', models.IntegerField()),
                ('c_debit', models.IntegerField()),
                ('c_balance', models.IntegerField()),
                ('c_success', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
