# Generated by Django 4.1.3 on 2022-11-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_alter_checking_c_acc_name_alter_checking_c_acc_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checking',
            name='c_debit_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='saving',
            name='s_debit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
