# Generated by Django 4.1.3 on 2022-11-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_checking_c_debit_date_saving_s_debit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checking',
            name='c_credit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checking',
            name='c_debit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='s_debit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
