# Generated by Django 4.1.3 on 2022-11-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_alter_checking_c_credit_alter_checking_c_debit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='s_credit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
